package com.course.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COURSE.
 */
public class COURSE {

    private Long id;
    private String coursenumber;
    private String name;
    private String category;
    private String teacher;
    private String time;
    private Float price;
    private String details;
    private String remark;
    private byte[] photo;

    public COURSE() {
    }

    public COURSE(Long id) {
        this.id = id;
    }

    public COURSE(Long id, String coursenumber, String name, String category, String teacher, String time, Float price, String details, String remark, byte[] photo) {
        this.id = id;
        this.coursenumber = coursenumber;
        this.name = name;
        this.category = category;
        this.teacher = teacher;
        this.time = time;
        this.price = price;
        this.details = details;
        this.remark = remark;
        this.photo = photo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCoursenumber() {
        return coursenumber;
    }

    public void setCoursenumber(String coursenumber) {
        this.coursenumber = coursenumber;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getTeacher() {
        return teacher;
    }

    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public byte[] getPhoto() {
        return photo;
    }

    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

}
