package com.course.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.course.greendao.USER;
import com.course.greendao.TEACHER;
import com.course.greendao.COURSE;
import com.course.greendao.SHOPPING;
import com.course.greendao.ORDER;
import com.course.greendao.SETTING;

import com.course.greendao.USERDao;
import com.course.greendao.TEACHERDao;
import com.course.greendao.COURSEDao;
import com.course.greendao.SHOPPINGDao;
import com.course.greendao.ORDERDao;
import com.course.greendao.SETTINGDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uSERDaoConfig;
    private final DaoConfig tEACHERDaoConfig;
    private final DaoConfig cOURSEDaoConfig;
    private final DaoConfig sHOPPINGDaoConfig;
    private final DaoConfig oRDERDaoConfig;
    private final DaoConfig sETTINGDaoConfig;

    private final USERDao uSERDao;
    private final TEACHERDao tEACHERDao;
    private final COURSEDao cOURSEDao;
    private final SHOPPINGDao sHOPPINGDao;
    private final ORDERDao oRDERDao;
    private final SETTINGDao sETTINGDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uSERDaoConfig = daoConfigMap.get(USERDao.class).clone();
        uSERDaoConfig.initIdentityScope(type);

        tEACHERDaoConfig = daoConfigMap.get(TEACHERDao.class).clone();
        tEACHERDaoConfig.initIdentityScope(type);

        cOURSEDaoConfig = daoConfigMap.get(COURSEDao.class).clone();
        cOURSEDaoConfig.initIdentityScope(type);

        sHOPPINGDaoConfig = daoConfigMap.get(SHOPPINGDao.class).clone();
        sHOPPINGDaoConfig.initIdentityScope(type);

        oRDERDaoConfig = daoConfigMap.get(ORDERDao.class).clone();
        oRDERDaoConfig.initIdentityScope(type);

        sETTINGDaoConfig = daoConfigMap.get(SETTINGDao.class).clone();
        sETTINGDaoConfig.initIdentityScope(type);

        uSERDao = new USERDao(uSERDaoConfig, this);
        tEACHERDao = new TEACHERDao(tEACHERDaoConfig, this);
        cOURSEDao = new COURSEDao(cOURSEDaoConfig, this);
        sHOPPINGDao = new SHOPPINGDao(sHOPPINGDaoConfig, this);
        oRDERDao = new ORDERDao(oRDERDaoConfig, this);
        sETTINGDao = new SETTINGDao(sETTINGDaoConfig, this);

        registerDao(USER.class, uSERDao);
        registerDao(TEACHER.class, tEACHERDao);
        registerDao(COURSE.class, cOURSEDao);
        registerDao(SHOPPING.class, sHOPPINGDao);
        registerDao(ORDER.class, oRDERDao);
        registerDao(SETTING.class, sETTINGDao);
    }
    
    public void clear() {
        uSERDaoConfig.getIdentityScope().clear();
        tEACHERDaoConfig.getIdentityScope().clear();
        cOURSEDaoConfig.getIdentityScope().clear();
        sHOPPINGDaoConfig.getIdentityScope().clear();
        oRDERDaoConfig.getIdentityScope().clear();
        sETTINGDaoConfig.getIdentityScope().clear();
    }

    public USERDao getUSERDao() {
        return uSERDao;
    }

    public TEACHERDao getTEACHERDao() {
        return tEACHERDao;
    }

    public COURSEDao getCOURSEDao() {
        return cOURSEDao;
    }

    public SHOPPINGDao getSHOPPINGDao() {
        return sHOPPINGDao;
    }

    public ORDERDao getORDERDao() {
        return oRDERDao;
    }

    public SETTINGDao getSETTINGDao() {
        return sETTINGDao;
    }

}
