package com.course.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOPPING.
 */
public class SHOPPING {

    private Long id;
    private Integer course_id;
    private Integer user_id;
    private java.util.Date addtime;

    public SHOPPING() {
    }

    public SHOPPING(Long id) {
        this.id = id;
    }

    public SHOPPING(Long id, Integer course_id, Integer user_id, java.util.Date addtime) {
        this.id = id;
        this.course_id = course_id;
        this.user_id = user_id;
        this.addtime = addtime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCourse_id() {
        return course_id;
    }

    public void setCourse_id(Integer course_id) {
        this.course_id = course_id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public java.util.Date getAddtime() {
        return addtime;
    }

    public void setAddtime(java.util.Date addtime) {
        this.addtime = addtime;
    }

}
